import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { menuDocument } from './menu';
import { FilePromotionRepository } from './promotion-repository';
import { calculateDiscountedPrice, isPromotionActive, type Promotion } from './promotion';
import { PromotionService } from './promotion-service';

const labels = (value: string) => ({ fr: `${value} FR`, en: `${value} EN`, ar: `${value} AR` });
async function service() { const dir = await mkdtemp(path.join(os.tmpdir(), 'viet-garden-promotions-')); return new PromotionService(new FilePromotionRepository(path.join(dir, 'promotions.json')), async () => structuredClone(menuDocument)); }
function input(type: Promotion['type'], rule: Promotion['rule']): Omit<Promotion, 'id'> { return { title: labels(type), description: labels('Description'), type, target: { itemIds: ['soupes-pho'] }, rule, enabled: true, sortOrder: 0 }; }

test('pricing calculations never produce negative prices', () => { assert.equal(calculateDiscountedPrice(100, 'percentage', 20), 80); assert.equal(calculateDiscountedPrice(20, 'fixed-amount', 30), 0); assert.throws(() => calculateDiscountedPrice(-1, 'fixed-amount', 1)); });
test('promotion active state respects enabled and date windows', () => { const now = new Date('2026-01-10T12:00:00Z'); const base = { ...input('percentage', { percentage: 20 }), id: 'p', enabled: true, startsAt: '2026-01-01T00:00:00Z', endsAt: '2026-01-31T00:00:00Z' }; assert.equal(isPromotionActive(base, now), true); assert.equal(isPromotionActive({ ...base, enabled: false }, now), false); assert.equal(isPromotionActive({ ...base, startsAt: '2026-02-01T00:00:00Z' }, now), false); });
test('service exposes only currently active promotions', async () => { const instance = await service(); await instance.createPromotion({ ...input('percentage', { percentage: 20 }), startsAt: '2026-01-01T00:00:00Z', endsAt: '2026-01-31T00:00:00Z' }); await instance.createPromotion({ ...input('fixed-amount', { fixedAmount: 10 }), startsAt: '2026-02-01T00:00:00Z', sortOrder: 1 }); assert.equal((await instance.listActivePromotions(new Date('2026-01-10T12:00:00Z'))).length, 1); });
test('all promotion types can be created with structured rules and automatic IDs', async () => { const instance = await service(); for (const [type, rule] of [['percentage', { percentage: 20 }], ['fixed-amount', { fixedAmount: 30 }], ['buy-x-get-y-free', { buyQuantity: 2, rewardQuantity: 1 }], ['buy-x-get-y-discount', { buyQuantity: 2, rewardQuantity: 1, rewardDiscountPercentage: 50 }], ['bundle-fixed-price', { bundlePrice: 99 }]] as const) { const created = await instance.createPromotion(input(type, rule)); assert.match(created.id, /^promotion-/); } assert.equal((await instance.listPromotions()).length, 5); });
test('promotion validation rejects missing targets, invalid rules, dates, and references', async () => { const instance = await service(); await assert.rejects(instance.createPromotion(input('percentage', { percentage: 101 })), /at most 100/); await assert.rejects(instance.createPromotion({ ...input('fixed-amount', { fixedAmount: 10 }), target: { itemIds: ['missing'] } }), /unknown menu item/); await assert.rejects(instance.createPromotion({ ...input('percentage', { percentage: 10 }), startsAt: '2026-02-01T00:00:00Z', endsAt: '2026-01-01T00:00:00Z' }), /before end/); await assert.rejects(instance.createPromotion({ ...input('bundle-fixed-price', { bundlePrice: 99 }), target: {} }), /at least one/); });
test('promotion CRUD, ordering, and removal preserve menu references', async () => { const instance = await service(); const first = await instance.createPromotion(input('percentage', { percentage: 10 })); const second = await instance.createPromotion({ ...input('fixed-amount', { fixedAmount: 10 }), sortOrder: 1, target: { categoryIds: ['soupes'] } }); const edited = await instance.updatePromotion(first.id, { enabled: false }); assert.equal(edited.enabled, false); const reordered = await instance.reorderPromotions([second.id, first.id]); assert.deepEqual(reordered.map((item) => item.id), [second.id, first.id]); await instance.deletePromotion(first.id); assert.equal((await instance.listPromotions()).length, 1); assert.equal(menuDocument.items.some((item) => item.id === 'soupes-pho'), true); });
